version: '3.9'

services:
  app:
    build: .
    container_name: chatbot-app
    env_file:
      - .env
    environment:
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./:/app
    ports:
      - "8000:8000"
      - "8501:8501"
    restart: unless-stopped
